filtered_rating_df = 'filtered-rating-df'
novice_rating_graph = 'Novice-rating-graph'
bronze_rating_graph = 'Bronze-rating-graph'
silver_rating_graph = 'Silver-rating-graph'
gold_rating_graph = 'Gold-rating-graph'
diamond_rating_graph = 'Diamond-rating-graph'
champion_rating_graph = 'Champion-rating-graph'
